### ISSUE TITLE
NPE in SecurityExtractor when using Basic Authentication

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#29]
This is related to #24 

With this definition, which is valid in RAML:
```yml
securitySchemes:
  - basic:
      type: Basic Authentication
```
I receive:
<pre>
java.lang.NullPointerException
	at guru.nidi.ramltester.core.SecurityExtractor.queryParameters(SecurityExtractor.java:46)
	at guru.nidi.ramltester.core.RamlChecker.checkQueryParameters(RamlChecker.java:146)
	at guru.nidi.ramltester.core.RamlChecker.checkRequest(RamlChecker.java:112)
	at guru.nidi.ramltester.core.RamlChecker.check(RamlChecker.java:68)
</pre>
Until #24 gets done, I think `raml-tester` should ignore the schemes it can't check (maybe log a warning about it) instead of dying with an NPE.

**Comment by nidi3** [comment]
The NPE is thrown for securitySchemes without describedBy. Clearly an error.
Unknown schemes are ignored, as you suggest.
