### ISSUE TITLE
Bogus warning if JSON example file contains string instead of object

### ISSUE THREAD

**Issue by greenrd** [nidi3/raml-tester#54]
If an example file contains just a string, which is legal JSON, instead of an object, a bogus warning is logged:

```
WARN  | 2015-10-01 18:26:16,662 | guru.nidi.ramltester.RelativeJsonSchemaAwareRamlDocumentBuilder - Could not parse json file example/authenticate.json. Relative $refs inside might not work.
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.Object] -> [simple type, class java.lang.Object]] from String value ('foo'); no single-String constructor/factory method
 at [Source: "foo"
; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:875)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:281)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:284)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:334)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3731)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2724)
	at guru.nidi.ramltester.RelativeJsonSchemaAwareRamlDocumentBuilder.onScalar(RelativeJsonSchemaAwareRamlDocumentBuilder.java:56)
	at org.raml.parser.visitor.NodeVisitor.visitScalar(NodeVisitor.java:256)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:222)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitMappingNode(NodeVisitor.java:86)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:218)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitMappingNode(NodeVisitor.java:86)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:218)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitMappingNode(NodeVisitor.java:86)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:218)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitMappingNode(NodeVisitor.java:86)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:218)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitMappingNode(NodeVisitor.java:86)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:218)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitMappingNode(NodeVisitor.java:86)
	at org.raml.parser.visitor.NodeVisitor.visit(NodeVisitor.java:218)
	at org.raml.parser.visitor.NodeVisitor.visitResolvedNode(NodeVisitor.java:180)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:151)
	at org.raml.parser.visitor.NodeVisitor.visitDocument(NodeVisitor.java:209)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:90)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:102)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:78)
	at guru.nidi.ramltester.RamlLoaders.load(RamlLoaders.java:188)
```

**Comment by greenrd** [comment]
The same problem happens for examples which are arrays.
