### ISSUE TITLE
Repeated query parameters yied IllegalArgumentException "Unhandled parameter value"

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#57]
Using version `0.8.5`, with a RestAssured request like:

    given().get("/things?id=1&id=2&id=3").then().assertThat().statusCode(is(200)));

I get:

<pre>
java.lang.IllegalArgumentException: Unhandled parameter value '[1,2,3]' of type class java.util.ArrayList
	at guru.nidi.ramltester.core.ParameterChecker.checkParameter(ParameterChecker.java:192)
	at guru.nidi.ramltester.core.ParameterChecker.checkListParameters(ParameterChecker.java:140)
	at guru.nidi.ramltester.core.ParameterChecker.checkExtendedParameters(ParameterChecker.java:121)
	at guru.nidi.ramltester.core.ParameterChecker.checkParameters(ParameterChecker.java:103)
	at guru.nidi.ramltester.core.RamlChecker.checkQueryParameters(RamlChecker.java:166)
	at guru.nidi.ramltester.core.RamlChecker.checkRequest(RamlChecker.java:129)
	at guru.nidi.ramltester.core.RamlChecker.check(RamlChecker.java:66)
	at guru.nidi.ramltester.restassured.RamlValidationFilter.filter(RamlValidationFilter.java:41)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at com.jayway.restassured.filter.Filter$filter$0.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:71)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1466)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:151)
	at com.jayway.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
</pre>

I've step-debugged in `ParameterChecker.checkListParameters` and found that `entry` at:

    for (final Object value : entry.getValue()) {

contains a List of List, i.e. it is: `{id=[[1,2,3]]}` where, I think, only a list was expected.

**Comment by ddossot** [comment]
Thanks a lot for the quick fix :bow: I'm happy to confirm that `0.8.6-SNAPSHOT` works fine with it :+1: 

Do you plan a release any time soon?

**Comment by nidi3** [comment]
done

**Comment by ddossot** [comment]
Thank you sir.
