### ISSUE TITLE
NPE when validating a POST request with no payload

### ISSUE THREAD

**Issue by martinpaoloni** [nidi3/raml-tester#65]
When attempting to check the results of a POST call with no payload, a NullPointerException occurs.

Test case code:
```java
    @Test
    public void testRequest() throws IOException {
        RamlDefinition api = RamlLoaders.fromClasspath(getClass()).load("concur_minimal.raml");
        Assert.assertThat(api.validator().withChecks(URI_PARAMETER, EXAMPLE, EMPTY, PARAMETER).validate(),
                validates());

        RamlHttpClient client = api.createHttpClient();
        HttpPost post = new HttpPost("https://www.concursolutions.com/api/company/v1.0/subscribe?type=profile");
        post.addHeader("Authorization", "OAuth xxxxxxxxxx");
        HttpResponse response = client.execute(post);

        Assert.assertThat(client.getLastReport(), checks());
    }
```
The first assertion works fine. The last one is the one failing.

Stacktrace:
```
java.lang.NullPointerException
	at guru.nidi.ramltester.httpcomponents.HttpComponentsRamlMessage.buffered(HttpComponentsRamlMessage.java:53)
	at guru.nidi.ramltester.httpcomponents.HttpComponentsRamlRequest.getContent(HttpComponentsRamlRequest.java:81)
	at guru.nidi.ramltester.core.CheckerHelper.hasContent(CheckerHelper.java:51)
	at guru.nidi.ramltester.core.MediaTypeMatch.find(MediaTypeMatch.java:66)
	at guru.nidi.ramltester.core.RamlChecker.checkRequest(RamlChecker.java:133)
	at guru.nidi.ramltester.core.RamlChecker.check(RamlChecker.java:68)
	at guru.nidi.ramltester.httpcomponents.RamlHttpClient.execute(RamlHttpClient.java:108)
	at guru.nidi.ramltester.httpcomponents.RamlHttpClient.execute(RamlHttpClient.java:118)
	at org.mule.AppTest.testRequest(AppTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by nidi3** [comment]
You're a good tester, thanks!
