### ISSUE TITLE
#68 reproduced - problem with include schemas ?

### ISSUE THREAD

**Issue by KenLomax** [nidi3/raml-tester#69]
Hi
The attached raml and test will fail if I do not have the two (empty) files, named precisely “tip” and “tips” (with no extension) alongside the api.raml

What I would expect, is that I can have the following in my api.raml entry:
schemas:
tip: !include schemas/tip.json
tips: !include schemas/tips.json
and the two files tip.json and tips.json in the schemas folder, which lives alongside api.raml

[ramlTesting.zip](https://github.com/nidi3/raml-tester/files/310443/ramlTesting.zip)

Error is:
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: guru.nidi.loader.Loader$ResourceNotFoundException: Resource '/schemas/tip' not found: java.io.FileNotFoundException: src/main/webapp/meta-data/schemas/tip (No such file or directory)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:110)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.processArray(InstanceValidator.java:188)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:149)
	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:56)
	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.main.JsonSchema.doValidate(JsonSchema.java:76)
	at com.github.fge.jsonschema.main.JsonSchema.validate(JsonSchema.java:109)
	at com.github.fge.jsonschema.main.JsonSchema.validate(JsonSchema.java:125)
	at guru.nidi.ramltester.validator.JsonSchemaValidator.validate(JsonSchemaValidator.java:83)
	at guru.nidi.ramltester.core.RamlChecker.checkSchema(RamlChecker.java:291)
	at guru.nidi.ramltester.core.RamlChecker.doCheckReponse(RamlChecker.java:268)
	at guru.nidi.ramltester.core.RamlChecker.checkResponse(RamlChecker.java:245)
	at guru.nidi.ramltester.core.RamlChecker.check(RamlChecker.java:70)
	at guru.nidi.ramltester.spring.RamlMatcher.testAgainst(RamlMatcher.java:54)
	at guru.nidi.ramltester.spring.RamlMatcher.match(RamlMatcher.java:47)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
	at com.hybris.yaaspathl.SpringTest.tips(SpringTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: guru.nidi.loader.Loader$ResourceNotFoundException: Resource '/schemas/tip' not found: java.io.FileNotFoundException: src/main/webapp/meta-data/schemas/tip (No such file or directory)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
	at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:107)
	at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:57)
	at com.github.fge.jsonschema.core.processing.ProcessorMap$Mapper.process(ProcessorMap.java:166)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 54 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: guru.nidi.loader.Loader$ResourceNotFoundException: Resource '/schemas/tip' not found: java.io.FileNotFoundException: src/main/webapp/meta-data/schemas/tip (No such file or directory)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.github.fge.jsonschema.core.load.SchemaLoader.get(SchemaLoader.java:172)
	at com.github.fge.jsonschema.core.load.RefResolver.rawProcess(RefResolver.java:114)
	at com.github.fge.jsonschema.core.load.RefResolver.rawProcess(RefResolver.java:51)
	at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:77)
	at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:41)
	at com.github.fge.jsonschema.core.processing.ProcessorChain$ProcessorMerger.process(ProcessorChain.java:189)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
	at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 68 more
Caused by: guru.nidi.loader.Loader$ResourceNotFoundException: Resource '/schemas/tip' not found: java.io.FileNotFoundException: src/main/webapp/meta-data/schemas/tip (No such file or directory)
	at guru.nidi.loader.basic.FileLoader.fetchResource(FileLoader.java:43)
	at guru.nidi.loader.basic.UriLoader.fetchResource(UriLoader.java:77)
	at guru.nidi.loader.use.jsonschema.LoaderUriDownloader.fetch(LoaderUriDownloader.java:37)
	at com.github.fge.jsonschema.core.load.URIManager.getContent(URIManager.java:104)
	at com.github.fge.jsonschema.core.load.SchemaLoader$1.load(SchemaLoader.java:115)
	at com.github.fge.jsonschema.core.load.SchemaLoader$1.load(SchemaLoader.java:109)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 84 more
Caused by: java.io.FileNotFoundException: src/main/webapp/meta-data/schemas/tip (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at guru.nidi.loader.basic.FileLoader.fetchResource(FileLoader.java:40)
	... 93 more

Thanks

**Comment by ddossot** [comment]
Loading schemas from a directory below the one where the RAML file is located is common practice and works fine. It should work for you too 😉 

I think the issue is related to the way you load the RAML spec, which prevents finding anything related to it:

   RamlLoaders.fromFile( "src/main/webapp/meta-data" ).load( "api.raml" )

This loads the file related to your project in your dev environment and will not work as so as you package your application. You should move `meta-data` under `src/main/resource` and load the RAML spec `fromClasspath`.

On a side note, `tips.json` is wrong, it should do `"$ref":"tip.json"` instead of `"$ref":"tip"`

**Comment by KenLomax** [comment]
Thank you Sir - excellent answer.
